import Head from "next/head";
import React, { useEffect, useState } from "react";

import Link from "next/link";
import Button from "~/components/common/Button";
import { useSession, signIn, signOut } from "next-auth/react";
import HomeComponent from "~/components/Home";
import UploadFiles from "~/components/UploadFiles";
import Showfiles from "~/components/ShowFiles";
import { collection, onSnapshot } from "firebase/firestore";
import { database } from "~/firebaseConfig";
export default function Home() {
  let files = collection(database, "files");
  const { data: session } = useSession();

  const [filelist, setfilelist] = useState<Arraytype>([]);
  const email = session?.user.email;

  useEffect(() => {
    return onSnapshot(files, (response) => {
      setfilelist(
        response.docs
          .map((item) => {
            return { ...item.data(), id: item.id };
          })
          .filter((item: any) => item.email === session?.user.email),
      );
    });
  }, [email]);

  return (
    <>
      <Head>
        <title>Google Drive</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-100vh flex flex-col ">
        <div className="container flex flex-col gap-1  px-4 py-1 ">
          <h1 className="flex items-end justify-end text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]"></h1>
        </div>
        <div className="mb-3 ml-3 flex"></div>
        <div className="ml-3">
          <Showfiles
            //@ts-ignore
            file={filelist}
          />
        </div>
      </main>
    </>
  );
}
